-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 16, 2024 at 03:26 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tourism`
--

-- --------------------------------------------------------

--
-- Table structure for table `destination`
--

CREATE TABLE `destination` (
  `Dest_ID` int(10) UNSIGNED NOT NULL,
  `Name` varchar(60) NOT NULL,
  `Address` text NOT NULL,
  `Fee` varchar(50) NOT NULL,
  `Type1` varchar(40) NOT NULL,
  `Type2` varchar(50) NOT NULL,
  `Type3` varchar(50) NOT NULL,
  `Type4` varchar(60) NOT NULL,
  `Type5` varchar(50) NOT NULL,
  `Type6` varchar(50) NOT NULL,
  `Tips` text NOT NULL,
  `Facilities` text NOT NULL,
  `Activities` text NOT NULL,
  `Time` varchar(50) NOT NULL,
  `Description` text NOT NULL,
  `Contact` text NOT NULL,
  `Image1` text NOT NULL,
  `Image2` text NOT NULL,
  `Image3` text NOT NULL,
  `Location` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `destination`
--

INSERT INTO `destination` (`Dest_ID`, `Name`, `Address`, `Fee`, `Type1`, `Type2`, `Type3`, `Type4`, `Type5`, `Type6`, `Tips`, `Facilities`, `Activities`, `Time`, `Description`, `Contact`, `Image1`, `Image2`, `Image3`, `Location`) VALUES
(1, 'Pintu Wang Gunung', 'Sungai Batu Pahat, 01000 Kangar, Perlis', 'Permit cost is RM5 and guide is needed', 'Hiking', 'Sightseeing', 'Adventure', 'Nature', '', '', 'Be sure to wear long sleeves clothes as they are mosquitos everywhere and wear sport shoes. Bring a hat and remember to use sunscreen. Make sure to follow proper hiking etiquettes. Having a glove on is also recommended. Make sure to grab breakfast and bring an optional packed lunch.\r\n', 'Parking bays and toilets are available at the food stalls opposite Taman Ular Dan Reptilia.', 'Hiking, Bird Watching, Nature Photography', 'Everyday, 7am – 6pm', 'A unique hiking destination that offers an exhilarating transboundary trekking experience between Malaysia and Thailand. Experience this 3.9-km out-and-back trail near Kangar, Perlis. This hike requires a permit from the Forestry Department before embarking on the journey.\r\n', '', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiIj12Z-d5PnjyIJAWe8w1FK7XG5gSH2XmD6xvthsgY6DKVHIldygL-Kw_E1Csa9YGzzPswHMRo9pbWJynkRe7RdzFrISsAnIwpsEWpNqmhJlNMwMbsDzDfvNkoGSkhy4UX_D2w7TCPiACCxxdHdS8GBMh7fw0hFSLjslK5P0ZaZYkLmhaIHRzs6Eb1/s1638/202', 'https://2.bp.blogspot.com/-A9d9QoMjAZA/W5fgv-4PTBI/AAAAAAAAQ5w/CVGeug0NV_oGOSulaU1IvV_M1pxwifj9ACKgBGAs/s1600/IMG-20180801-WA0017.jpg', 'https://i.ytimg.com/vi/f7NCSxcOgX0/maxresdefault.jpg', 'https://maps.app.goo.gl/8SpascTdbJrquexy5'),
(2, 'Taman Negeri Perlis', 'Wang Kelian, 02200 Kaki Bukit, Perlis, Malaysia', 'View down ', 'National Park', 'Healing', '', '', '', '', 'Must refer to MGP if enter the forest', 'Dormitories, seminar hall, chalets, prayer room, toilets, gazebo, campsite, observation tower, open hall, and cafeteria.', 'Exploring Wang Burma Cave, Birdwatching\r\nTrail exploration, Photography, Night walk, Camping, Nature education, Hiking Mount Perlis, Enjoying the scenic views of the river and limestone caves\r\n', 'Everyday except Wednesday, 9am – 7pm', 'Later', 'Tel : 604 - 9765 966 Fax : 604 - 9767 901', 'https://heroesofadventure.com/wp-content/uploads/2019/07/Screen-Shot-2016-10-28-at-10.09.26.jpg', 'https://3.bp.blogspot.com/-5jafElgEaIk/UYhhJt76vFI/AAAAAAAAhHQ/MGNZNmjvSRU/w640-h480/Taman+Negeri+Perlis.JPG', 'https://file.mahalo.cz/2015/09/Taman-Negeri-Perlis-1024x683.jpg', 'https://maps.app.goo.gl/7eBdnnhReESLWQ9w6'),
(3, 'Pasar Terapung JPS Perlis', 'Kompleks Jps Perlis, Pengkalam Asam,01000, 01000 Kangar, Perlis', 'Free', 'Lake', 'Market', 'Cultural', 'Calm', '', '', 'Come early so that the stalls still open', 'Restroom at the entrance, parking available ', 'Fish feeding, mini petting zoo, boat cycling', 'Saturday – Sunday, 9am – 7pm', 'A vibrant market located in Perlis, Malaysia, where vendors sell a variety of goods directly from boats. This market not only showcases local produce and crafts but also serves as a cultural experience, attracting both locals and tourists who wish to enjoy the unique atmosphere of shopping on water23. The market has gained popularity for its picturesque setting and the opportunity it provides to engage with the local community while savoring traditional Malaysian delicacies.', 'https://www.facebook.com/PasarTerapungJPS/', 'https://cdn.libur.com.my/2023/06/304847713_3271406986477145_6961527573202606894_n.jpg', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEggIMvq0tPd38FDLUeynh_OwfYoiSeOxb9RA-5PN6DG12eX6qA_9qA_ISV_FEBwk6zM7GAJ405-xXz9Jz4OP4hm6v-9uXMuMTIvc4BFBfBnXFsuGymdu5wIZF9NZxqoppcFKdSztixS0ZyLrvaafJwXUS5Ss2oDTWU0XtER-DimHwbA1FG9xt61yGgssTDK/s1280', 'https://malaysiaaktif.my/wp-content/uploads/2023/11/WhatsApp-Image-2023-11-14-at-10.41.57-1.jpeg', 'https://maps.app.goo.gl/ApDFpySN46cznzoBA'),
(4, 'Perlis Snake Park', 'Sungai Batu Pahat, 01000 Kangar, Perlis, Malaysia', 'fill up later', '', '', '', '', '', '', 'Call to check if sunflower in season, bring mini fan if come during hot season', 'Parking no fee, toilets, bike for rent', 'Petting Zoo, educational tours, photography', '9am – 5pm', 'Snake and Reptile Farm is a tourist attraction, learning centre and shelter to various species of snakes and reptiles. The farm has succeeded in gathering more than 150 venomous snakes and non-venemous snakes from Malaysia and from overseas.', 'https://www.facebook.com/TamanUlar/\r\n04-976 8511\r\ntamanularperlis@gmail.com', 'https://apicms.thestar.com.my/uploads/images/2024/06/20/2758950.JPG', 'https://media-cdn.tripadvisor.com/media/photo-s/0f/8f/d3/59/snake-and-reptile-farm.jpg', 'https://images-sg.girlstyle.com/wp-content/uploads/2020/07/Sunflower-field-Malaysia-Taman-Ular-Dan-Reptilia-Negeri-Perlis-Snake-Park5.png?quality=90', 'https://maps.app.goo.gl/qpUdwjzUgWcHwb2dA'),
(5, 'Padang Waremart', 'Jalan Padang, Padang Besar 02100 Malaysia', 'Free', '', '', '', '', '', '', 'Come during weekdays. Check wheather', 'Plenty of parking spots except during weekend, toilet', 'Window Shopping, Food tasting', '8am - 8pm', 'Padang Waremart is a bustling retail center located in Padang Besar, Perlis, Malaysia, known for its diverse range of products. Visitors can find an array of items including clothes, shoes, handbags, kitchenware, and local snacks, making it a popular shopping destination for both locals and tourists alike. The market offers a v atmosphere where shoppers can enjoy bargaining while exploring the various stalls filled with unique goods and delicious treats.', 'https://www.facebook.com/PadangWaremart/\r\n012-575 7007', 'https://media-cdn.tripadvisor.com/media/photo-s/1a/4b/7a/71/20191212-151847-largejpg.jpg', 'https://lh5.googleusercontent.com/p/AF1QipPBK_Sv_NWAoJup5Vu4daCZPtrtfHNWSRLHmVhU=w1080-k-no', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgalj7VD5VBVgc3QEAQneVh0M2etLXeXBcdF1OD5D_yixgvaLpUkASLSJ_Vos4CApJNQh-ajPhKmpWA9urbX4o3zC0_LH34unLxU8O-pJZY1L-N9uEEwmr1yk1r0LNq5F7cTIsadqpWJ6E7Pc7QuKlDCvozzQ5bBeHTZg_MVTVEic62BOqHqSDPwo2x/s2000/IMG', 'https://maps.app.goo.gl/rd5Ztei6XwNEpqDD7'),
(6, 'Kangar Street Art', 'Lorong Seni, Pusat Bandar Kangar, 01000 Kangar, Perlis', 'Free', '', '', '', '', '', '', 'Check weather', 'Lots of cafe and restaurant, plenty of parking spots', ' Taking photos, enjoying art, short tour ', '24 hours', 'It is translated through a mural on the walls of a building in the center of the city. It is an attraction for the public as well as tourists who come to the State of Perlis. This mural was drawn by Secondary School visual arts education students from all over the country through the \"Kangar Street Art\" program in conjunction with the National Level Arts Festival 2016 on 9 October 2016.\r\n', '', 'https://www.tourismmalaysiablog.de/wp-content/uploads/2022/09/88011185_148657036604323_14130558367956992_n.jpeg', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjTMcFprHsx_ew-9wfn7f95U0V-sXhYJb2JLtvx6CxDZ4y-elL-9FoMdW4cbD_vEUPC6o_jDgiJz-376s6lwz_8xTUUg-ZcdI20DFCI2C5fj5bUmget6CV9tdgz6zkiQk50ILBA2O97iLPVV8mdNikKRVhgomeIQLa99e3nEA7X5N0cheKNmASpALsNng/s1431/K', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgccm443jtc05gANFTijt0Gt5t7pWZYy0eWEoC7jXdUSP_O2gdeuAtHqjARXqlWdOslV-J-ACphFUjUIT5IDbac74975ZUNXvao752OCdmbwXEGsADObtKZSIzeIBeVGdDP4oiroH4MWG_B2SYmSr8clUA1fiQb0Pjj9JwmIeUNtHUJTLZPaNjZXLCI-A/s1430/K', 'https://maps.app.goo.gl/NNUBUZBoBDhprjg38'),
(7, 'Taman Buah Buahan Eksotik Perlis', 'Kampung Lembah Tuwi, 01000 Kangar, Perlis', 'Adult: RM2, kid: RM1', '', '', '', '', '', '', 'Wear hat, use sunscreen', 'Parking, Rest huts, Prayer room, Toilets\r\nFruit stalls, Photoshoot spot, Fish lakes\r\n', 'Scooter riding, fish feeding, fruit eating, Picnic, Relaxing, Walking, Photoshoot\r\nBuy fruit products at fruit stalls, Kayaking', 'Everyday except Monday, 9am – 6.30pm', 'Taman Buah-Buahan Eksotik Perlis is a unique fruit park located in Perlis, Malaysia, showcasing a wide variety of exotic fruits native to the region. Visitors can enjoy interactive experiences, including fruit tasting and guided tours, making it an educational and enjoyable destination for families and tourists alike. The park features lush landscapes and vibrant fruit trees, offering a picturesque setting for exploring the diversity of tropical fruits.', 'https://www.facebook.com/perlisgrapes/\r\n04-938 4466\r\nperlis@doa.gov.my', 'https://gokelah.com/wp-content/uploads/2022/03/taman-buah-buahan-eksotik-negeri-perlis-1.jpg?resize=480%2C480', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhumP-Oxfyr7GExwIy4y-UQvfNk_eaW35f1YnLDzY5ZARcnX2Br5LrfV9Cb0zRAUZj-5iAHjg3nCey3BenF_goywsZBI-hE0_p8ngZmZaMYvEhAg3XznAjfH86Yc_9qZAkHZ-X6bTSBvaPAG1ZFBR8ig5ukpN5DTMA3HR8t5Fk3It44vXp2e4ojxQsR_g/s1366/C', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgizd6VD6F4rLrRFLjttjfYTQSK805iGodBbhblGIghyx6wGTOZwhPSN_zy5okFJQaovW9P7qHp9BVjOnE_4284p00Oom3Kn4jZO8jxmdyMg29oKZ1XiwlpIA9cPHc-CsAfvPOMl8WS_dyl1tKiGOng2GJbei6Oy8n5RCM6ibuQzaK2K0cvk3zXsYHlmw/s1366/C', 'https://maps.app.goo.gl/upQmNNs51DcLVe6A7'),
(8, 'Taman Bunga Kertas Tuanku Lailatul Shahreen', 'Laman Cenderawasih, 01000, Kangar, Perlis', 'Free', '', '', '', '', '', '', 'Wearing comfortable shoes is recommended as the garden features walking trails', 'Rest huts, Running trails, A pond', 'Sightseeing, walking and jogging, Taking photos', '24 hours', 'Taman Bunga Kertas Tuanku Lailatul Shahreen, or Tuanku Lailatul Shahreen’s Paper Flower Garden, is a great place to visit for all flower enthusiasts, specifically bougainvillaea enthusiasts. Dozens of colourful bougainvillaea, also known as paper flowers because they look like coloured paper, bloom in this four-hectare garden named after the Queen of Perlis.', '', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgZ8lQVaun9GWcw-92uxRwjM4n3oy9A0Uvi3hSkb2SL7_7kDupq3i9U2DRiwCXgO10tmcrJkdkQDZNSD1ZEYQKJe8jBWjcWbSIFSeor1U_vzr0cmo-GdhjmjzcIXcGbwgzf7z5oT4a1Pll95hg3lmqPOslNr_KCKIBhvNI8XDI4Pg44m_RQjS-ovCss/s2000/IMG', 'https://myweekendplan.asia/wp-content/uploads/2023/01/Admire-The-Flowers-At-The-Taman-Bunga-Kertas-Tuanku-Lailatul-Shahreen-1.jpg', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/be/bf/33/photo4jpg.jpg?w=1200&h=1200&s=1', 'https://maps.app.goo.gl/X4mNhqxmiyHeYuwbA'),
(9, 'Timah Tasoh Dam Square', 'Kampung Bukit Manek, 02400, Kangar, Perlis', 'Free', '', '', '', '', '', '', 'Visit early in the morning/late afternoon for cooler temperatures and stunning views', 'Rest areas, Camping sites, Parking', 'Kayaking and boating, Fishing, Bird-watching, Photography', '8am - 7pm', 'Timah Tasoh Dam Square, also known as Dataran Empangan Timah Tasoh, is a scenic recreational area located near the Timah Tasoh Dam in Perlis, Malaysia. This picturesque spot offers a variety of leisure activities, including cycling, photography opportunities against stunning natural backdrops, and access to facilities such as parking and restrooms. The square serves as a hub for visitors looking to enjoy the beautiful surroundings of the dam and engage in outdoor pursuits like kayaking and fishing at the nearby freshwater fish sanctuary.', '', 'https://assets.nst.com.my/images/articles/SANTUARI_IKAN_AIR_TAWAR_TIMAH_TASOH_n01_1704810487.jpg', 'https://live.staticflickr.com/5711/30095698203_bc3484e222_b.jpg', 'https://thesmartlocal.my/wp-content/uploads/2020/12/93797675_3988455041172610_7816039377475096148_n.jpg', 'https://maps.app.goo.gl/wVC7t14uASTC3tXL7'),
(10, 'Perlis Herbal Forest', 'Jalan Kaki Buki, 01000, Kangar, Perlis', 'Adults: RM2, Kids: RM1', '', '', '', '', '', '', 'Bring guidebook or app as some of plants are not labeled to enhance better experience', 'Nature walks, Orchid gardens, Nursery, Rest areas, Parking ', 'Plant exploration, Herbal foot soak, Massage, Take photos ', '8am - 5pm', 'Taman Rimba Herba located at Sungai Batu Pahat, Perlis is a park for all the collections of medicinal plants that are used especially by locals.  The park is opened for visitors who are keen to learn about the types of usage of these plants.  The collection of plants consists of wild plants that grow around this park (in-situ) and medicinal plants that are from other areas (ex-situ).', '', 'https://thumbs.dreamstime.com/b/perlis-herbal-forest-herb-garden-located-next-to-ayer-bukit-park-was-first-opened-public-covers-area-%E2%80%8B%E2%80%8B-158700327.jpg', 'https://static.wixstatic.com/media/0de0c8_b4b32abc5aeb4550bff00f6f89bb6d12~mv2.jpg/v1/fill/w_980,h_734,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/0de0c8_b4b32abc5aeb4550bff00f6f89bb6d12~mv2.jpg', 'https://assets.hmetro.com.my/images/articles/03hm18zx55_1520026029.jpg', 'https://maps.app.goo.gl/27G6WP7tDGw3ZYW97'),
(11, 'Bukit Ayer Forest Eco Park', 'Jalan Anak Chelong, 01000, Kangar', 'Adults : RM2, Kids: RM1', '', '', '', '', '', '', 'Bring picnic mat to rest under the tree ', 'Food stalls, Toilet, Swimming pool, Parking', 'Hiking, Picnic, Swimming, Nature-watching', 'Everyday except Wednesday 8am - 7pm', 'Bukit Ayer Forest Eco Park, known as Taman Eko-Rimba Bukit Ayer, is situated approximately 13 kilometers from Kangar in Perlis, Malaysia. Nestled within the Bukit Bintang Forest Reserve, this eco-park features a rich hill dipterocarp forest, offering visitors a chance to explore its natural beauty through activities like jungle trekking and swimming in both natural and man-made pools.', '', 'https://media.getaran.my/images/uploads/covers/_large/Hutan_Lipur_Bukit_Ayer_-_gambar_BERNAMA.jpeg', 'https://surgaroute.com/wp-content/uploads/2022/12/322017447_884450285900682_169926253197819375_n-1024x788.jpg', 'https://cdn.libur.com.my/2024/01/Eqslq3DVEAMY3Cq.jpg', 'https://maps.app.goo.gl/P2n9NVcZVpjZsyKH9'),
(12, 'Alwi Mosque', 'Pusat Bandar Kangar, 01000, Kangar, Perlis', 'Free', '', '', '', '', '', '', 'Wear modest attire and women should cover their heads', 'Prayer hall, Toilet, Rest areas', 'Pray, Religious events, Cultural exploration', '5am - 10pm', 'Alwi Mosque, or Masjid Alwi, is the oldest mosque in Perlis, Malaysia, located in Kangar. Constructed between 1931 and 1933 during the British colonial period, it features distinctive Mughal architectural elements, including an onion-shaped dome sitting on an octagonal drum and a Mughal-style minaret with a chattri balcony. The mosque is adorned with pointed arches and multiple mini domes, creating a visually striking presence that reflects its historical significance and cultural heritage', '', 'https://assets.nst.com.my/images/articles/0302_masjid_alwi_1517663069.jpg', 'https://2.bp.blogspot.com/_-qBpApnovQQ/SVCmH3g4ZOI/AAAAAAAANi4/M59sbbnLTko/s400/17PC200017.JPG', 'https://myweekendplan.asia/wp-content/uploads/2023/01/Visit-The-Alwi-Mosque-1-550x733.jpg', 'https://maps.app.goo.gl/DPog6zcmz7oC4AX98'),
(13, 'Arked Niaga Padang Besar', 'Jalan Pusat Bandar, 01000, Kangar, Perlis', 'Free', '', '', '', '', '', '', 'Bring cash as some stalls didnt accept online transaction and cards', 'Food stalls, parking, local goods, toilets', 'Dining, Window shopping', '9am - 6pm', 'The two storey arcade has shops selling clothes and souvenirs, catering mostly to locals as well as the working class. The central atrium has an airwell providing natural light into the area below. The location of Arked Niaga Padang Besar makes it possible for people from across the border to come over for shopping, though some regard shopping on the Thailand side makes more sense.', '', 'https://apicms.thestar.com.my/uploads/images/2021/11/27/1383243.jpg', 'https://www.penang-traveltips.com/0-pics/timtye/pics/malaysia/arked-niaga-padang-besar.jpg', 'https://2.bp.blogspot.com/-w4VD5aG77Nw/VsAYA1ZcJEI/AAAAAAAATXc/J9mWWsgzB80/s1600/DSCN5348%255B1%255D.JPG', 'https://maps.app.goo.gl/gFbYcWoCEFmZQ5S67'),
(14, 'Perlis Ostrich Farm', '7, 02100 Padang Besar, Perlis', 'Adults : RM2, Kids: RM1', '', '', '', '', '', '', 'Wear comfortable shoes recommended to walk around ', 'Parking, Visitor center, Benches', 'Animal feeding and petting, photography', '10am - 7pm', 'A unique attraction that houses several ostriches and offers visitors an interactive experience with these large birds. Guests can feed and pet the ostriches, and even purchase ostrich eggs to take home, enhancing their visit with memorable encounters. The farm also features various activities such as ATV rides and archery, making it a fun destination for families and adventure seekers.', '', 'https://1.bp.blogspot.com/_C026BqO3DEo/S_FFEVakOFI/AAAAAAAAA48/Equ2ywjMWQs/s640/P4150738.JPG', 'https://i.ytimg.com/vi/cZVHutsi2Eo/maxresdefault.jpg', 'https://2.bp.blogspot.com/-x2T1oQosqY4/TdoKr5YBjAI/AAAAAAAAAEo/mMCCW_z7cs8/s1600/12032011118.jpg', 'https://maps.app.goo.gl/ZkJUwq4hWha23eCJ8'),
(15, 'Pengkalan Asam Trails Recretional Park', 'Taman Pengkalan Asam, 01000, Kangar, Perlis', 'Free', '', '', '', '', '', '', 'Bring water to stay hydrated to hike or walk for long time period', 'Walking and cycling trails, Playground, Chalet, Toilet, Hanging bridge ', 'Hiking and jogging, Cycling, Picnic, Photography', '8am - 7pm', 'Pengkalan Asam offers a scenic trail that takes you through the picturesque surroundings of the Perlis River and small villages. Along the way, simple facilities for leisure and exercise are provided, allowing visitors to engage in recreational activities while enjoying the breathtaking scenery and diverse flora and fauna. This trail is suitable for cycling enthusiasts. One of the highlights of the trail is the presence of a hanging bridge.\r\n\r\n', '', 'https://i.ytimg.com/vi/1u9EL9SJUFQ/maxresdefault.jpg', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/f5/32/95/caption.jpg?w=600&h=600&s=1', 'https://radarpena.com/wp-content/uploads/2023/10/Pengkalan-Asam-Trails-Recreational-Park.jpg', 'https://maps.app.goo.gl/H4FPLSeSJn8CCjaH9'),
(16, 'Kelam Cave', 'Jalan, Kaki Bukit, 02200 Kaki Bukit, Perlis', 'Adults: RM2-5 Kids:RM1-2', '', '', '', '', '', '', 'Wear comfortable, non-slippery footwear due to damp surfaces.', 'Small food stall,picnic areas and suspension bridge providing access into the cave.', 'Cave exploration,River views,Nature walk,Photography and Picnicking.', 'Daily: 8:00 AM - 6:00 PM', 'One of the most unique caves in Malaysia as it\'s a 370-metre long limestone cave where it\'s famous for its \'cave walk\'. It\'s among the favorites cave for the adventure seekers. You will enter from one end of the cave and come out at a different location. The only path in is via a wooden suspension bridge measuring 8 ft wide walkway.', '+604 976 5966', 'https://img.astroawani.com/2022-06/41655397781_GuaKelam.jpg', 'https://3.bp.blogspot.com/-K-ff64wYUvk/VZs7HYvD_dI/AAAAAAAADX8/n814RAgkn2A/s1600/gua-kelam-01.jpg', 'https://static.flickr.com/11/96310617_10e784eb34.jpg', 'https://maps.app.goo.gl/oDbNKKEzFQkfJfpB7'),
(17, 'Wang Kelian Viewpoint', '02200 Kaki Bukit, Perlis', 'View down ', '', '', '', '', '', '', 'The area can be foggy in the early morning, giving a beautiful misty view of the surrounding landscape.', 'Parking area, Resting Shelters at the top, Restrooms, Food Stalls.', 'Scenic Viewing, Photography,Nature Watching', 'Daily: 6:30 am- 6:30 pm', 'The Wang Kelian Viewpoint is conveniently accessible from the roadside. The path leads you to the viewpoint where you can admire the surrounding mountains in Wang Kelian. The view is stunning, offering a picturesque sight of the landscape. Visitors can witness breathtaking sunrises and sunsets from this vantage point.', '', 'https://1.bp.blogspot.com/-ADeYdOh1K2k/YQyknOxpCLI/AAAAAAAAEcA/dtnvtGOabUU1MvByfd6vEdQ4IWQfu2SdgCLcBGAsYHQ/s2048/IMG_20210406_094036.jpg', 'https://blogger.googleusercontent.com/img/a/AVvXsEhR89yBa9AUQeJnnEN5NoWQ9nNwiIxbiQj7Rhpl3S3HN7wdWowHfIl7W-Uvf3DSPJDiKnf_2r1MD4KhCpiBsLB5Uto_4ZDmflSyGBa24o2EcPmVTwo0EiiCjT0qiOGx2aNbf4XGTDSC6CjjkI1asu9W1Y0Fy3XfePYM0-WeMBtP591wxIGbUIKruND6Bw=w640-h360', 'https://img.freepik.com/premium-photo/beautiful-wang-kelian-view-point-perlis-malaysia_33482-472.jpg', 'https://maps.app.goo.gl/9ywLwqtf19VkJZjGA'),
(18, 'Kota Kayang Museum', '02000 Kuala Perlis, Perlis', '', '', '', '', '', '', '', 'If you’re a history enthusiast, this museum provides insight into Perlis\' history, the Malay Sultanate, and archaeological findings.', 'Parking Area,Restrooms,Exhibition Halls,Outdoor Gardens and Souvenir Shop.', 'Museum Tours, photography and heritage walk.', 'Tuesday to Sunday: 9:00 AM – 5:00 PM', 'The area surrounded by Bukit Kayang, Bukit Lambong Panah, Bukit Jagat Hutang, Bukit Wai and Bukit Menara. This museum was established in an area that was once site of the palace where the Royal Kedah-Perlis family resides. This is based on historical relics found around areas such as the Tomb of Sultan Dhiauddin Al-Mukarram Shah Ibni Al-Marhum Sultan Muhyiddin Mansur Shah (15th Sultan of Kedah who built a city near the Wai River which was named as Indera Kayangan).', 'https://www.facebook.com/mzmkotakayang/\r\nmuziumkotakayang.2022@gmail.com\r\n+6019-4472684', 'https://gowhere.my/wp-content/uploads/2015/10/Kota-Kayang-Museum.jpg', 'https://s3media.freemalaysiatoday.com/wp-content/uploads/2018/11/Kota-Kayang-Museum-lifestyle-271118-2.jpg', 'https://transport.neocities.org/kayang.jpg', 'https://maps.app.goo.gl/zXo6taVZ4PFJ4QwC8'),
(19, 'Tasik Melati Recreational Park', 'Jalan Tasik Melati, Tasik Melati, 02400 Kangar, Perlis', 'Free', '', '', '', '', '', '', 'Great for families, nature lovers, and casual joggers or walkers.', 'Playground, Sheltered Gazebos, Walking Paths around the lake.\r\n', 'Walking & Jogging, Picnicking, Photography and Children’s Playground.', 'Open 24 hours', 'Tasik Melati offers a serene setting for morning relaxation. Spanning a considerable area, it provides ample space for various activities. There is an expansive lake and numerous pavilions. Visitors can engage in leisurely jogs or play with their children amidst the scenic surroundings.', '', 'https://media-cdn.tripadvisor.com/media/photo-s/0f/90/25/3a/tasik-melati-recreational.jpg', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgW8-dF6HiPoKJAHiMmqCvgMH4R0njwTG5MbYBsQMCsk7AxcSlpk7od0FwTUW344b_RN7xsF3wjTQzsi49-FLZbs_M4C_TaMGy1XFN6cf9J2iXijEK_-hL1v4YNlcCZ25GmVaNKq3-89GSnXmgRN8B-4pU3xcHF4-fM-6TV_02yTVML7a3ASQeMuRlJRQ/w360-h6', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjrfdUHLycuhtD48xibR-Yi-sfpLXfyOA9z8cRMys9lvRPJ_D9CPx_zH5EARYp86U1JXtbT3kBHli6ZcfDJlHblj9WDNjjUi5xUp1WZZZmbnX2nUHykvdkXsp0_CZySACP-hXNw3MeiH2vEtLHP5KRF3wYJvFakIQyVR8Rs_Dc789P55u5ALlcVEJGV1Q/s1431/T', 'https://maps.app.goo.gl/HS8Dxpv9MgC2H4aG9'),
(20, 'Bukit Kubu Recreational Forest', 'Kampung Bukit Kubu, 02000 Kuala Perlis, Perlis, Malaysia', 'Free', '', '', '', '', '', '', 'Be prepared for a mild workout, as the climb up the hill can be a bit steep for beginners.', 'Parking Area, Restrooms,Sheltered Gazebos,Well-paved Hiking Trails up to the hilltop and Picnic Areas', 'Hiking,Cave Exploration,Picnicking,Photography and Nature Walks.', 'Daily: 7am-6pm', 'Nestled amidst the serene landscapes of Kuala Perlis, this hidden gem offers a breathtaking spectacle. Surrounded by the lush expanse of rice fields and the rugged contours of limestone hills, a lookout point awaits, providing unparalleled views. When the vista opens up, extending over Sungai Perlis to the enchanting islands of Southern Thailand.', '', 'https://1.bp.blogspot.com/-6IOUrk9svyg/TcZHgP8nyPI/AAAAAAAAAZw/wk3BgrcaJ64/s1600/bukitkubu3.jpg', 'https://photos.wikimapia.org/p/00/00/53/54/06_big.jpg', 'https://tempatwisataunik.com/wp-content/uploads/2019/07/117a09ac-bukit-kubu.jpg', 'https://maps.app.goo.gl/QB7LihJ5eVcQsJ2KA'),
(21, 'Al-Hussain Mosque', '1, Persiaran Putra Timur, 02000 Kuala Perlis, Perlis', 'Free', '', '', '', '', '', '', 'Dress modestly when visiting the mosque.', 'Prayer Halls, Restrooms, Parking Area and Sea View Platforms.', 'Praying for muslims, sightseeing, Photography and Cultural Exploration.', 'Daily: 5am-10pm', 'The Al-Hussein Mosque, located in Kuala Perlis, Malaysia, is one of the world\'s first floating mosques, officially opened on October 8, 2011. Built on stilts above the Straits of Malacca, it creates the illusion of floating and features a modern design that incorporates natural elements such as coral stones and marble. With a hexagonal twin-peak minaret symbolizing the six tenets of Iman in Islam, the mosque serves as a place of worship and a stunning architectural landmark that attracts visitors, especially during sunset when it is beautifully illuminated.\r\n', '', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/d9/cb/d1/al-hussain-mosque-floating.jpg?w=1200&h=1200&s=1', 'https://media-cdn.tripadvisor.com/media/photo-s/1b/be/c6/3b/photo9jpg.jpg', 'https://mymasjid.photo-digital.org/wp-content/uploads/2012/03/alhussain_04.jpg', 'https://maps.app.goo.gl/GBfErBrWCHByuEst7'),
(22, 'Ladang Nipah Kipli', '02700 Kuala Sanglang, Perlis', 'Free', '', '', '', '', '', '', 'Try to visit during the harvest season for a more vibrant experience.', 'Parking Area,Restrooms,Information Booth and Shaded Areas for resting', 'Plantation Tours,Tasting,Photography and Nature Walks', 'Daily:12:30pm - 6:30pm', 'Amidst the serene beauty of Perlis lies the Ladang Nipah Kipli, a farm dedicated to nurturing over 2000 nipah palm trees. Located in the charming Kampung Tanah Timbul of Kuala Sanglang, this plantation not only offers a glimpse into the art of palm cultivation but also provides visitors with an opportunity to dine in the midst of the rustling palms. Soak in the tranquil surroundings and relish a unique culinary experience that will leave you feeling refreshed and rejuvenated.', '017-4306245', 'https://1.bp.blogspot.com/-IktKktoIjXw/XoREa_GR1FI/AAAAAAAAWb8/aZyvXU8u3bcKS_ZfIRjeuj4U53cJxC8tQCLcBGAsYHQ/s1600/DSC07028.JPG', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/1e/58/6e/ladang-nipah-kipli.jpg?w=1200&h=1200&s=1', 'https://2.bp.blogspot.com/--pM0AanYR8Q/XMZwd4HCwkI/AAAAAAAARmE/Rw11eVLomB06JS2H0ZNGZGfDvfhrt7bqACLcBGAs/s1600/20180930_181239.jpg', 'https://maps.app.goo.gl/P9o6fZXps8bNezQv9'),
(23, 'Gua Wang Burma', '02200 Kaki Bukit, Perlis', 'Free', '', '', '', '', '', '', 'Be prepared for humidity and potential insects; bring insect repellent.', 'Parking Area, Restrooms, Information Signboards providing details about the cave', 'Cave Exploration, Photography, Nature Walks and Birdwatching', 'Generally open daily', 'Known for its streams and exotic species of insects and fungi, the cave system is divided into two main caves: The less challenging and more scenic one is Wang Burma 1, with its unique rock formations comprising of stalactites, stalagmites and columns, and Wang Burma 2, which is physically and mentally challenging with its dark hooks and turns, of narrow passages and muddy tunnels, you will need to crawl or squeeze your way through to reach the amazing water-worn rock formations in the inner part of the cave.', 'Tel : 604 9765 066\r\nFax: 604 9767 901', 'https://live.staticflickr.com/65535/52202773477_053a01f42d_b.jpg', 'https://live.staticflickr.com/65535/52203906611_b4814bd28d_b.jpg', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgnVo32sEWstammdM5v1xCJE9XwGwRmcm9dEj43xOJTBkjLszfEW1BlkpfNCVugZeZ39qLNOo6gvOY3x-l_YkAw3hpfzcOGk1w0TZlO31RR0PHpVOwQj7w43q8OdgmZv7twqmxAUqnXMf-P/s1600/IMG_20181020_163221.jpg', 'https://maps.app.goo.gl/LzjvCeS2AurSZDqv6');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `destination`
--
ALTER TABLE `destination`
  ADD UNIQUE KEY `Dest_ID` (`Dest_ID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
